### ISSUE TITLE
Please call for appointment

### ISSUE THREAD

**Issue by skmar** [azgs/az-wine#10]
Hi @jessica-azgs @Lbookman 

My question is related to both the form and the map. Also I'm not sure if this is something I can change myself. 

When none of the "Call/by appointment" are checked on the form...the "Please call for appointment" still shows up on the winemaker info on the sidebar. Can it be changed so "Please call for appointment" does not show up unless one of the "Call/by appointment" is checked?

Is this the right place for this question or should it go to azwinemap Github?

--Stephanie

**Comment by jessicagood** [comment]
Moved to https://github.com/azgs/azwinemap/issues/1
