### ISSUE TITLE
Issue with permissions, maybe?

### ISSUE THREAD

**Issue by skmar** [azgs/az-wine#11]
@jessica-azgs and @Lbookman 

One of our winemakers brought this to my attention.

The winemakers are not able to make edits to a vineyard that was added from their account when we make edits as an admin (when the winemakers log into their account they don't see any vineyards associated with their account even though the vineyard was created with that account). I was able to fix the issue for that winemaker but I want to know if there is something that can be done so this does not happen. I see that I have access to change permissions, but I don't want to change things without talking with you guys first.

I hope I explained the issue clearly.

Thanks,
Stephanie

**Comment by skmar** [comment]
**This only works when you know the password of the winemaker user.** 

Here's a work around when a winemaker user can not see the content that should be associated with their account. 

The work around is not ideal (it does not work easily when you don't know the password of the user), here are the steps I took:
- While logged in as the admin
  - Change the specific winemaker user permissions to "Superuser" status (not a good idea but it's temporary) 
  - Note: I use a browser that allows private browsing, so I can be logged in to two different accounts in the same browser
- While logged into the account of the user whose permissions that has been given "Superuser" status
  - Find and open the content that should be associated with their account and then click on "Save" (at the bottom of the page)
  - After you do this the content will be again associate this account
- **Immediately change the users permissions back to "Staff" status**
  - Note: I do this on the admin account
- The content that was "Saved" under the user accounts should now be visible and editable by that winemaker user

**Do not leave the winemaker user permissions as Superuser.**

**Comment by jessicagood** [comment]
Fixed with commit https://github.com/azgs/azwine/commit/5ca214d5948eb00a922ef57518e9955342d4046b. Added ability for a superuser to "hijack" another account to make edits.
