### ISSUE TITLE
add location ability for single entries

### ISSUE THREAD

**Issue by ridavis** [azgs/az-wine#6]
Is it possible for a user to add a location without creating an additional account? What if the people want to display their tasting room and winery at their vineyard, but also have a tasting room in downtown Tucson? Assuming the products they offer are the same, is there a way to make it so one entry could display multiple points?

**Comment by jessicagood** [comment]
If we're talking about a single business entity having multiple coordinates that gets tricky and would not be a trivial change. How many entities do you think would this apply to - where ALL properties, including hours, contact address, etc would be exactly the same? Unless it's going be a lot and is worth several days of work it's probably going to be better for a user to just create a second location under their account for the additional location.

**Comment by ridavis** [comment]
OK, I just didn't want them to have to create a new account. I'm totally satisfied if they can create multiple locations as a single user. I think this was an initial criteria, but so many users have screwed ed up and created several user accounts that I wasn't sure if that was an ability they had. Sorry for the confusion, it's been a while since I've worked with the map.

**Comment by jessicagood** [comment]
I had no issues creating multiple locations under my one test account. I'm going to mark this as closed but we can reopen if you notice something wrong with it or change your mind.
