### ISSUE TITLE
Year format

### ISSUE THREAD

**Issue by skmar** [azgs/az-wine#7]
Hi Laura and Jessica, 

I want to know if you can edit the year established format field right now it's YYYY-MM-DD but can we also add in YYYY, so that we don't have to have to enter it in as YYYY-01-01? If this is not doable can it be changed to just YYYY? Would this change mean that we would lose data?

I hope I'm posting in the right section.

Thanks,
Stephanie

**Comment by jessicagood** [comment]
Yes, this is the right section, thanks @skmar! I changed the code to let you enter in a year, month and day (or leave any of them blank). I didn't update the website yet though because changing the format this way will mean that all of the dates will need to be re-entered. Let me know when you are ready for me to update the live site.

**Comment by skmar** [comment]
Thanks for changing this, Jessica.

Before you update the live site I need to coordinate with Mike so he knows that we’ll have to re-enter the date info.

**Comment by skmar** [comment]
@jessica-azgs,

I'm looking for an easy way to see a list of all of the date established. Is it possible to add new column to the Users page that shows the date established, http://winedb.arizonaexperience.org/admin/auth/user/?

@fmichaelconway

**Comment by jessicagood** [comment]
@skmar The link you sent me is the link to the list of users (which doesn't have an established field) but I was able to add the established field to the admin [list of vineyards](http://winedb.arizonaexperience.org/admin/azwine/vineyard).

**Comment by skmar** [comment]
That is great! Thanks so much for doing that @jessica-azgs and for directing me to the correct list. Being able to see which have dates and what they are will make it easier for us to re-enter the info.

I'll let you know when I get the information copied so you can update the live site. 

@fmichaelconway

**Comment by jessicagood** [comment]
@skmar @fmichaelconway Before you are ready for me to change the live site you may want to consider if you even really want boxes for the month and day or if year by itself gives the user enough information.

**Comment by fmichaelconway** [comment]
I think the year is sufficient and clearly so do most vendors, becuase that is all they provide.
Mike

**Comment by skmar** [comment]
It does seem like that is how the vendors provide...@jessica-azgs do you think there should be another type of information?

**Comment by jessicagood** [comment]
@skmar I'm not sure what you mean by "another type of information" but in the new version of the form input if you only want boxes for the year, instead of month and day, I can do that. Or I can keep the month and day boxes in there. However you guys want it.

**Comment by fmichaelconway** [comment]
80%+ of the wine vendors only provide year established. Let's follow suit. M

**Comment by jessicagood** [comment]
Ok, do you have all of the established date information off the current site? It will go away when I update the live site and the year will have to be reentered in the new field. Let me know when you're ready for me to change it.

**Comment by skmar** [comment]
What I should have said was another format. I think we should keep the option for year, month, day but  have the ability to enter just year or year and month because it's less limiting.

**Comment by jessicagood** [comment]
@skmar I'm just going to change the field to a text box and then someone can enter whatever form they want for the date. Before it was a specific datefield type which has certain restrictions. We're not doing any sorting or searching on the established field so it doesn't matter if everyone enters the date in the same way or not. Sound ok?

**Comment by fmichaelconway** [comment]
Sounds good to me.
M

**Comment by skmar** [comment]
Sounds good. I copied down date established info, so you can update the live site whenever you can.

**Comment by jessicagood** [comment]
Ok, live site is updated. We actually didn't end up losing the original values that were in there.

**Comment by skmar** [comment]
Yay! I'm glad we didn't lose the original values. Thanks @jessica-azgs.
