### ISSUE TITLE
Another new column?

### ISSUE THREAD

**Issue by skmar** [azgs/az-wine#8]
Hi @Lbookman and @jessica-azgs,

From issue, 147818612, https://github.com/azgs/azwinemap/issues/8.

Is there a way to add the type of business field to the list of vineyards, http://winedb.arizonaexperience.org/admin/azwine/vineyard/, like Jessica did for the date established?

@fmichaelconway

**Comment by jessicagood** [comment]
@skmar Done

**Comment by skmar** [comment]
You are awesome!
